services:
  api:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '5056:8080'
    depends_on:
      - postgres
    environment:
      - WAIT_HOSTS=postgres:5432
      - WAIT_HOSTS_TIMEOUT=60
    network_mode: bridge

  postgres:
    image: postgres:14.7-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=triagemsys
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    network_mode: bridge
